# Starting with PyTorch

### What is a Tensor?
A tensor is an object that represents some data, that could be numbers, text, an image, a video, an audio... Tensors can have any number of dimensions.


In [1]:
import torch
torch.__version__

'2.0.0+cu117'

In [5]:
# Scalars (zero dimensions tensors)

scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


In [10]:
# Vectors (one dimension tensors)

vector = torch.tensor([7, 8])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 8])
1
torch.Size([2])


In [11]:
# Matrix (two dimensions tensors)
matrix = torch.tensor([[7, 8],
                       [9, 10]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [12]:
# Tensor

tensor = torch.tensor([[[1, 2],
                        [3, 4],
                        [5, 6]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])
3
torch.Size([1, 3, 2])


In [14]:
# Random tensor

rand_tensor = torch.rand(size=(3, 4))
print(rand_tensor)
print(rand_tensor.ndim)
print(rand_tensor.shape)
print(rand_tensor.dtype)

tensor([[0.8887, 0.5524, 0.5456, 0.4987],
        [0.5029, 0.3588, 0.1898, 0.1935],
        [0.6177, 0.3890, 0.5506, 0.2935]])
2
torch.Size([3, 4])
torch.float32


In [16]:
# Zeroes and ones
zeros_tensor = torch.zeros(size=(3, 4))
ones_tensor = torch.ones(size=(3, 4))

# Range tensors
zero_to_ten_tensor = torch.arange(start=0, end=10, step=1)
print(zero_to_ten_tensor)

# Copy with zeros
ten_zeros_tensor = torch.zeros_like(input=zero_to_ten_tensor)
print(ten_zeros_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
