# Starting with PyTorch

### What is a Tensor?
A tensor is an object that represents some data, that could be numbers, text, an image, a video, an audio... Tensors can have any number of dimensions.


In [3]:
import torch
torch.__version__

'2.0.0+cu117'

In [4]:
# Scalars (zero dimensions tensors)

scalar = torch.tensor(7)
print(scalar)
print(scalar.ndim)
print(scalar.item())

tensor(7)
0
7


C:\Users\thoma\AppData\Local\Temp\ipykernel_9060\2450826113.py:3: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/devdocs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  scalar = torch.tensor(7)


In [5]:
# Vectors (one dimension tensors)

vector = torch.tensor([7, 8])
print(vector)
print(vector.ndim)
print(vector.shape)

tensor([7, 8])
1
torch.Size([2])


In [6]:
# Matrix (two dimensions tensors)
matrix = torch.tensor([[7, 8],
                       [9, 10]])
print(matrix)
print(matrix.ndim)
print(matrix.shape)

tensor([[ 7,  8],
        [ 9, 10]])
2
torch.Size([2, 2])


In [7]:
# Tensor

tensor = torch.tensor([[[1, 2],
                        [3, 4],
                        [5, 6]]])
print(tensor)
print(tensor.ndim)
print(tensor.shape)

tensor([[[1, 2],
         [3, 4],
         [5, 6]]])
3
torch.Size([1, 3, 2])


In [8]:
# Random tensor

rand_tensor = torch.rand(size=(3, 4))
print(rand_tensor)
print(rand_tensor.ndim)
print(rand_tensor.shape)
print(rand_tensor.dtype)

tensor([[0.3119, 0.5098, 0.4707, 0.0870],
        [0.6088, 0.6877, 0.5566, 0.6515],
        [0.9109, 0.0716, 0.8094, 0.8587]])
2
torch.Size([3, 4])
torch.float32


In [9]:
# Zeroes and ones
zeros_tensor = torch.zeros(size=(3, 4))
ones_tensor = torch.ones(size=(3, 4))

# Range tensors
zero_to_ten_tensor = torch.arange(start=0, end=10, step=1)
print(zero_to_ten_tensor)

# Copy with zeros
ten_zeros_tensor = torch.zeros_like(input=zero_to_ten_tensor)
print(ten_zeros_tensor)
ten_zeros_tensor.device

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


device(type='cpu')

In [10]:
"""
Possible errors:

Using two tensors that have different datatypes (float 16 and float 32)
Using a different device (CPU or GPU)
Using two tensors with different sizes

"""

"""
Get informations from tensors:
tensor.shape
tensor.dtype
tensor.device

"""


'\nGet informations from tensors:\ntensor.shape\ntensor.dtype\ntensor.device\n\n'

## Basic operations

In [26]:
tensor = torch.tensor([1, 2, 3])
print(tensor + 10)
print(tensor * 2)
print(tensor - 5)
print(tensor / 2)

tensor = tensor + 10
print(tensor)

# Change data type
print(f"\n{tensor.dtype}")
tensor = tensor.type(torch.float16)
print(tensor.dtype)

tensor([11, 12, 13])
tensor([2, 4, 6])
tensor([-4, -3, -2])
tensor([0.5000, 1.0000, 1.5000])
tensor([11, 12, 13])

torch.int64
torch.float16


#### Matrix mulitplication
It's one of the most common operation in ml and dl. 
There are 2 rules for matrix multiplication:
1. The inner dimensions must match:
    - (3, 2) @ (3, 2) won't work
    - (3, 2) @ (2, 3) will work
    - (2, 3) @ (3, 2) will work
2. The resulting matrix has the shape of the outer dimensions:
    - (2, 3) @ (3, 2) -> (2, 2)
    - (3, 2) @ (2, 3) -> (3, 3)

| Operation | Calculation | Code |
| --- | --- | --- |
| Element-wise multiplication | [1\*1, 2\*2, 3\*3] = [1, 4, 9] | tensor * tensor |
| Matrix multiplication | [1\*1 + 2\*2 + 3\*3] = [14] | tensor.matmul(tensor) |



In [13]:
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([5, 8, 0])
torch.matmul(tensor1, tensor2)

tensor(21)

In [18]:
# This will raise an Exception
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.mm(tensor_A, tensor_B) # (this will error)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [16]:
# To make it work, we need to transpose the tensor:
final_tensor = torch.mm(tensor_A, tensor_B.T)
final_tensor

tensor([[ 76., 103.],
        [100., 136.]])

In [28]:
torch.manual_seed(42)

linear = torch.nn.Linear(in_features=2, out_features=3)
x = torch.tensor(
    [
     [1, 2],
     [3, 4],
     [5, 6]
    ],
    dtype=torch.float32
)

output = linear(x)
print(f"Input shape: {x.shape}")
print(f"Output shape: {output.shape}, \n\n{output}")

Input shape: torch.Size([3, 2])
Output shape: torch.Size([3, 3]), 

tensor([[1.3702, 1.5487, 0.7538],
        [3.6252, 2.5165, 0.7293],
        [5.8802, 3.4843, 0.7048]], grad_fn=<AddmmBackward0>)


##### Tensors reshaping

| Method                         | One-line description                                                                                     |
|--------------------------------|--------------------------------------------------------------------------------------------------------|
| torch.reshape(input, shape)    | Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().                           |
| torch.Tensor.view(shape)       | Returns a view of the original tensor in a different shape but shares the same data as the original tensor.|
| torch.stack(tensors, dim=0)    | Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.            |
| torch.squeeze(input)           | Squeezes input to remove all the dimensions with value 1.                                               |
| torch.unsqueeze(input, dim)    | Returns input with a dimension value of 1 added at dim.                                                |
| torch.permute(input, dims)     | Returns a view of the original input with its dimensions permuted (rearranged) to dims.                 |




In [30]:

x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [31]:
x = x.reshape(1, 7)
x, x.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [33]:
z = x.view(1, 7) # changing the view modifies also the real tensor
z[0, 0] = 99
z, z.shape, x, x.shape


(tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.]]),
 torch.Size([1, 7]),
 tensor([[99.,  2.,  3.,  4.,  5.,  6.,  7.]]),
 torch.Size([1, 7]))

In [39]:
x_stacked = torch.stack([x, x], dim=1)
x_stacked, x_stacked.shape

(tensor([[[99.,  2.,  3.,  4.,  5.,  6.,  7.],
          [99.,  2.,  3.,  4.,  5.,  6.,  7.]]]),
 torch.Size([1, 2, 7]))

In [40]:
# remove all single dimensions
x_squeezed = x.squeeze()
x.shape, x_squeezed.shape

(torch.Size([1, 7]), torch.Size([7]))

### Use PyTorch on GPU

In [44]:
device = "cuda" if torch.cuda.is_available() else "cpu"
tensor = torch.tensor([1, 2, 3], device=device)


False